---
#- debug:
#    msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"

- name: Copy Zabbix Agent file to remote server
  copy:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/
    owner: zabbix
    group: zabbix
    mode: 0644


- name: Configure Server line
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: ^Server=.*
    insertafter: ^# Server=
    line: Server={{ item }}
  with_items: "{{ zabbixserver }}"


- name: Configure Server Active line
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: ^ServerActive=.*
    insertafter: ^# ServerActive=
    line: ServerActive={{ item }}
  with_items: "{{ zabbixserver }}"

- name: Restart service zabbix-agent
  service:
      name: zabbix-agent
      state: restarted
