---
- name: Get Zabbix for Centos 7
  get_url:
          url: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-agent-4.0.20-1.el7.x86_64.rpm
          dest: /tmp/zabbix-release.rpm
          mode: '0440'
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Install Zabbix Release package
  yum:
   name: /tmp/zabbix-release.rpm
   state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'


- name: Install zabbix-agent
  yum:
    name: zabbix-agent
    state: latest
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'


- name: Enable zabbix-agent on boot
  systemd:
     enabled: yes
     name: zabbix-agent
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'


#- name: Restart service zabbix-agent
#  service:
#      name: zabbix-agent
#      state: restarted
#  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
